from typing import Protocol, List, Optional
from disscube.models import GridSpec, SpatialSource, DerivedVariable, SpatialRelation

class CatalogStore(Protocol):
    def save_grid(self, grid: GridSpec) -> None: ...
    def get_grid(self, grid_id: str) -> Optional[GridSpec]: ...
    def list_grids(self) -> List[GridSpec]: ...

    def save_spatial_source(self, source: SpatialSource) -> None: ...
    def get_spatial_source(self, source_id: str) -> Optional[SpatialSource]: ...
    def list_spatial_sources(self) -> List[SpatialSource]: ...
    
    def save_derived(self, derived: DerivedVariable) -> None: ...
    def search_derived_variables(self, grid_id: str | None = None, role: str | None = None, tile_id: str | None = None) -> List[DerivedVariable]: ...
    def get_derived_by_hash(self, spec_hash: str) -> Optional[DerivedVariable]: ...

    def save_relation(self, relation: SpatialRelation) -> None: ...
    def get_relations(self, grid_id: str) -> List[SpatialRelation]: ...
    def get_relation(self, source_id: str, target_id: str) -> Optional[SpatialRelation]: ...
