from typing import Protocol, List, Optional
from disscube.models import GridSpec, DataSource, DerivedVariable, SpatialRelation

class CatalogStore(Protocol):
    def save_grid(self, grid: GridSpec) -> None: ...
    def get_grid(self, grid_id: str) -> Optional[GridSpec]: ...
    def list_grids(self) -> List[GridSpec]: ...

    def save_source(self, source: DataSource) -> None: ...
    def get_source(self, source_id: str) -> Optional[DataSource]: ...
    def list_sources(self) -> List[DataSource]: ...
    
    def save_derived(self, derived: DerivedVariable) -> None: ...
    def search_derived(self, grid_id: str | None = None, role: str | None = None) -> List[DerivedVariable]: ...
    def get_derived_by_hash(self, spec_hash: str) -> Optional[DerivedVariable]: ...

    def save_relation(self, relation: SpatialRelation) -> None: ...
    def get_relations(self, grid_id: str) -> List[SpatialRelation]: ...
    def get_relation(self, source_id: str, target_id: str) -> Optional[SpatialRelation]: ...
