from typing import Protocol

from disscube.models import DerivedVariable, GridSpec, SpatialRelation, SpatialSource


class CatalogStore(Protocol):
    def save_grid(self, grid: GridSpec) -> None: ...
    def get_grid(self, grid_id: str) -> GridSpec | None: ...
    def list_grids(self) -> list[GridSpec]: ...

    def save_spatial_source(self, source: SpatialSource) -> None: ...
    def get_spatial_source(self, source_id: str) -> SpatialSource | None: ...
    def list_spatial_sources(self) -> list[SpatialSource]: ...
    
    def save_derived(self, derived: DerivedVariable) -> None: ...
    def delete_derived(self, derived_id: str) -> None: ...
    def search_derived_variables(self, grid_id: str | None = None, role: str | None = None, tile_id: str | None = None) -> list[DerivedVariable]: ...
    def get_derived_by_hash(self, spec_hash: str) -> DerivedVariable | None: ...

    def save_relation(self, relation: SpatialRelation) -> None: ...
    def get_relations(self, grid_id: str) -> list[SpatialRelation]: ...
    def get_relation(self, source_id: str, target_id: str) -> SpatialRelation | None: ...
